version = 3

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[palette]
#
# All used colors are mapped here!
# Modify to change theme
#
os_fg = '#000000'
os_bg = '#F0F0F0'
root_fg = '#FFFB38'
root_bg = '#ef5350'
path_fg = '#2d3436'
path_bg = '#FF9248'
lang_fg = '#000000'
lang_bg = '#5aa95a'
git_fg = '#011627'
git_bg = '#FFFB38'
git_bg_behind = '#C792EA'
git_bg_ahead = '#C792EA'
git_bg_ahead_and_behind = '#c5e478'
git_bg_changed = '#ffeb95'
git_staging_changed = '#ef5350'
exec_time_fg = '#ffffff'
exec_time_bg = '#83769c'
battery_fg = '#262626'
battery_bg = '#f36943'
battery_bg_charging = '#b8e994'
battery_bg_discharging = '#fff34e'
battery_bg_full = '#33DD2D'
date_fg = '#ffffff'
date_bg = '#40c4ff'
prompt_ok = '#e0f8ff'
prompt_err = '#ef5350'

#===================================================================================
# First line - left side
#
[[blocks]]
type = 'prompt'
alignment = 'left'

#-----------------------------------------------------------------------------------
# Operating System Icon
#
[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
foreground = 'p:os_fg'
background = 'p:os_bg'
type = 'os'
style = 'diamond'

[blocks.segments.properties]
linux = ''
macos = ''
windows = ''
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------
# Root user
#
[[blocks.segments]]
trailing_diamond = ''
template = '<parentBackground></>  '
foreground = 'p:root_fg'
background = 'p:root_bg'
type = 'root'
style = 'diamond'
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------
# Current Path
#
[[blocks.segments]]
trailing_diamond = ' '
foreground = 'p:path_fg'
background = 'p:path_bg'
type = 'path'
style = 'diamond'

[blocks.segments.properties]
folder_icon = '  '
home_icon = '  '
max_depth = 3
style = 'agnoster_full'

# [blocks.segments.properties.mapped_locations]
"~/dotfiles" = "★dotfiles"
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------
# Languages
#
[[blocks.segments]]
trailing_diamond = ' '
template = 'Python {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
foreground = 'p:lang_fg'
background = 'p:lang_bg'
type = 'python'
style = 'diamond'

[[blocks.segments]]
trailing_diamond = ' '
template = 'Go {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = 'p:lang_fg'
background = 'p:lang_bg'
type = 'go'
style = 'diamond'

[[blocks.segments]]
trailing_diamond = ' '
template = 'Rust {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = 'p:lang_fg'
background = 'p:lang_bg'
type = 'rust'
style = 'diamond'

[[blocks.segments]]
trailing_diamond = ' '
template = 'Zig {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = 'p:lang_fg'
background = 'p:lang_bg'
type = 'zig'
style = 'diamond'

#-----------------------------------------------------------------------------------
# Github
#
[[blocks.segments]]
trailing_diamond = ' '
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<p:git_staging_changed>  {{ .Staging.String }}</>{{ end }} '
foreground = 'p:git_fg'
background = 'p:git_bg'
type = 'git'
style = 'diamond'
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:git_bg_changed{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:git_bg_ahead_and_behind{{ end }}',
  '{{ if gt .Ahead 0 }}p:git_bg_ahead{{ end }}',
  '{{ if gt .Behind 0 }}p:git_bg_behind{{ end }}',
]

[blocks.segments.properties]
branch_icon = ' '
fetch_status = true
fetch_upstream_icon = true
#-----------------------------------------------------------------------------------

#===================================================================================
# First line - right side
#
[[blocks]]
type = 'prompt'
alignment = 'right'

#-----------------------------------------------------------------------------------
# Execution time
#
[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = '⏲ {{ .FormattedMs }}'
foreground = 'p:exec_time_fg'
background = 'p:exec_time_bg'
type = 'executiontime'
style = 'diamond'

[blocks.segments.properties]
style = 'roundrock'
threshold = 0
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------
# Battery
#
[[blocks.segments]]
trailing_diamond = ''
template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '
foreground = 'p:battery_fg'
background = 'p:battery_bg'
type = 'battery'
style = 'diamond'
background_templates = [
  '{{if eq "Charging" .State.String}}p:battery_bg_charging{{end}}',
  '{{if eq "Discharging" .State.String}}p:battery_bg_discharging{{end}}',
  '{{if eq "Full" .State.String}}p:battery_bg_full{{end}}',
]
invert_powerline = true

[blocks.segments.properties]
charged_icon = ' '
charging_icon = ' '
discharging_icon = ' '
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------
# Date and Time
#
[[blocks.segments]]
trailing_diamond = ''
template = '  {{ .CurrentDate | date .Format }} '
foreground = 'p:date_fg'
background = 'p:date_bg'
type = 'time'
style = 'diamond'
invert_powerline = true

[blocks.segments.properties]
time_format = "Mon 3:04 PM"
#-----------------------------------------------------------------------------------

#===================================================================================
# Second line
#
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '» '
foreground = 'p:prompt_ok'
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}p:prompt_err{{ end }}']

[blocks.segments.properties]
always_enabled = true
#===================================================================================
