# Add basic aliases
alias ls="eza --icons=always"
alias ll="ls -l"
alias lt="ls -lt"
alias la="ls -al"
alias godev="cd $PROJECTS"
alias gopro="cd $PROJECTS"
alias godot="cd $DOTFILES"
# Add go-related aliases
alias gor="go run ."
alias got="go test -v ./..."
alias goi="go install"
alias gou="go clean -i"
alias gob="go build"
alias gogo="cd $PROJECTS/Go"
# Add rust-related aliases
alias gorust="cd $PROJECTS/Rust"
alias ci="cargo install --path ."
alias cr="cargo run -q --"
alias ct="cargo test"
alias crb="cargo run -q --bin"
alias ctb="cargo test --bin"
# Add zig-related aliases
alias gozig="cd $PROJECTS/Zig"
alias zbr="zig build run"
alias zbt="zig build test --summary all"
alias zfr="zig fetch --save https://github.com/raysan5/raylib/archive/refs/tags/5.5.tar.gz"
# Add more advanced aliases
alias edit="$EDITOR"
alias remove="rm -rf"
alias reload="source ~/.zshrc"
alias vim=nvim
alias vienv="vim ~/.env"
alias viconf="vim ~/.zshrc.flevin58"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias vscodium="/Applications/VSCodium.app/Contents/MacOS/Electron"
alias tree="tree --gitignore"
alias tree2="tree --gitignore -L 2"
alias tree3="tree --gitignore -L 3"
alias brewup="brew update && brew upgrade"
