# Add basic aliases
alias ls="eza --icons=always"
alias ll="ls -l"
alias lt="ls -lt"
alias la="ls -al"
alias godev="cd $PROJECTS"
alias gopro="cd $PROJECTS"
alias godot="cd $DOTFILES"
alias man="batman"
alias sport="sudo port"
alias gozig="cd $PROJECTS/Zig"
alias zbr="zig build run"
alias zbt="zig build test --summary all"
alias zfr="zig fetch --save https://github.com/raysan5/raylib/archive/refs/tags/5.5.tar.gz"
# Add more advanced aliases
alias edit="$EDITOR"
alias remove="rm -rf"
alias reload="source ~/.zshrc"
alias vim=nvim
alias vienv="vim ~/.env"
alias viconf="vim ~/.zshrc.flevin58"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias vscodium="/Applications/VSCodium.app/Contents/MacOS/Electron"
alias tree="tree --gitignore"
alias tree2="tree --gitignore -L 2"
alias tree3="tree --gitignore -L 3"
alias brewup="brew update && brew upgrade"
